---
apiVersion: v1
kind: Service
metadata:
    name: infisical-agent-injector-svc
    labels:
        app.kubernetes.io/name: infisical-agent-injector
        app.kubernetes.io/instance: infisical
spec:
    ports:
        - name: https
          port: 443
          targetPort: 8585
    selector:
        app.kubernetes.io/name: infisical-agent-injector
        app.kubernetes.io/instance: infisical
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
    name: infisical-agent-injector-cfg
    labels:
        app.kubernetes.io/name: infisical-agent-injector
        app.kubernetes.io/instance: infisical
webhooks:
    - name: org.infisical.com
      sideEffects: None
      admissionReviewVersions:
          - "v1"
          - "v1beta1"
      clientConfig:
          service:
              name: "infisical-agent-injector-svc"
              namespace: "{{ .Release.Namespace }}"
              path: "/mutate"
          caBundle: ""
      rules:
          - operations: ["CREATE"]
            apiGroups: [""]
            apiVersions: ["v1"]
            resources: ["pods"]
            scope: "Namespaced"
      namespaceSelector: {}
      objectSelector:
          matchExpressions:
              - key: app.kubernetes.io/name
                operator: NotIn
                values: ["infisical-agent-injector"]
      failurePolicy: "{{ .Values.failurePolicy }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: infisical-agent-injector-configmap-reader
    labels:
        app.kubernetes.io/name: infisical-agent-injector
        app.kubernetes.io/instance: infisical
rules:
    - apiGroups: [""]
      resources: ["configmaps"]
      verbs:
          - "get"
          - "watch"
          - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: infisical-agent-injector-configmap-binding
    labels:
        app.kubernetes.io/name: infisical-agent-injector
        app.kubernetes.io/instance: infisical
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: infisical-agent-injector-configmap-reader
subjects:
    - kind: ServiceAccount
      name: infisical-agent-injector
      namespace: "{{ .Release.Namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: infisical-agent-injector-clusterrole
    labels:
        app.kubernetes.io/name: infisical-agent-injector
        app.kubernetes.io/instance: infisical
rules:
    - apiGroups: ["admissionregistration.k8s.io"]
      resources: ["mutatingwebhookconfigurations"]
      verbs:
          - "get"
          - "list"
          - "watch"
          - "patch"
    - apiGroups: [""]
      resources: ["nodes"]
      verbs:
          - "get"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: infisical-agent-injector-binding
    labels:
        app.kubernetes.io/name: infisical-agent-injector
        app.kubernetes.io/instance: infisical
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: infisical-agent-injector-clusterrole
subjects:
    - kind: ServiceAccount
      name: infisical-agent-injector
      namespace: "{{ .Release.Namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: infisical-agent-injector-secrets-pods-role
    labels:
        app.kubernetes.io/name: infisical-agent-injector
        app.kubernetes.io/instance: infisical
rules:
    - apiGroups: [""]
      resources: ["secrets"]
      verbs:
          - "create"
          - "get"
          - "watch"
          - "list"
          - "update"
    - apiGroups: [""]
      resources: ["pods"]
      verbs:
          - "get"
          - "patch"
          - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: infisical-agent-injector-secrets-pods-binding
    labels:
        app.kubernetes.io/name: infisical-agent-injector
        app.kubernetes.io/instance: infisical
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: infisical-agent-injector-secrets-pods-role
subjects:
    - kind: ServiceAccount
      name: infisical-agent-injector
      namespace: "{{ .Release.Namespace }}"
